print("Hello World!")
print("What is your name?")
my_name = input()
print("It is good to meet you, {}".format(my_name))
print("The length of your name is: {}".format(len(my_name)))
print("What is your age?")
my_age = input()
print("You will be {} in a year.".format(int(my_age) + 1))
